[workspace]
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["conda-forge"]
name = "josh-external-sources"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
climakitae = ">=1.2.3, <2"
